name: pre-release-ci
on:
  push:
    tags:
      - 'v*'
jobs:
  acceptance-test:
    name: acceptance-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Tests
        run: make testacc
        env:
          COCKROACH_API_KEY: ${{ secrets.COCKROACH_API_KEY }}
